server:
  port : 8083

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
  
#spring:
#  data:
#    mongodb:
#      database: Product
#      host: mongo
#      port: 27017
#      uri: mongo://localhost:27017/product-service
      
spring:
  application:
    name: "order-service"
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/mydatabase
    username: root
    password: 1234
  jpa:
    hibernate.ddl-auto: update
    generate-ddl: true
    show-sql: true
    properties:
      hibernate:
        format_sql: true      